language: node_js
node_js:
  - '10'

before_deploy:
  - yarn build-demo

deploy:
  provider: pages
  local-dir: demo
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
